# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrocuota', models.CharField(max_length=200)),
                ('mes', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('anioocuota', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroregisro', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(help_text='Ingrese el nombre del usuario', max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(help_text='Ingrese el fecha de nacimiento en formato AAAA-MM-DD, por ejemplo: 1990-06-15')),
                ('nrosocio', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('cbu', models.IntegerField(null=True)),
                ('dar_baja', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='', max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registropagos',
            name='socio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemasocioscap.Socio'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemasocioscap.RegistroPagos'),
        ),
    ]
