# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0002_auto_20200811_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pago',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
