# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0003_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrocuota', models.IntegerField()),
                ('anioocuota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemasocioscap.Anual')),
            ],
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del usuario', max_length=200),
        ),
    ]
