# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0003_auto_20200915_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropagos',
            old_name='numeroregisro',
            new_name='numeroregistro',
        ),
    ]
