# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-18 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0005_auto_20200717_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroregisro', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='mes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
