# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-18 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0006_auto_20200718_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='registropago',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemasocioscap.RegistroPagos'),
        ),
    ]
