# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0007_auto_20200915_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
