# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0007_socio_registropago'),
    ]

    operations = [
        migrations.AddField(
            model_name='anual',
            name='registro_anio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemasocioscap.RegistroPagos'),
        ),
    ]
