# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0008_anual_registro_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='mes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Ingrese el fecha de nacimiento en formato AAAA-MM-DD, por ejemplo: 1990-06-15'),
        ),
    ]
