# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0008_auto_20200915_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='anioocuota',
            new_name='aniocuota',
        ),
    ]
