# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0009_auto_20200721_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='registropago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemasocioscap.RegistroPagos'),
        ),
    ]
