# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0009_auto_20200915_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cuota',
            name='aniocuota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
