# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-16 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0010_auto_20200916_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anio',
            name='anio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='aniocuota',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
