# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0010_auto_20200721_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anual',
            name='registro_anio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemasocioscap.RegistroPagos'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='anioocuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemasocioscap.Anual'),
        ),
    ]
