# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-16 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0011_auto_20200916_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='aniocuota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
