# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0011_auto_20200721_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='dar_baja',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='', max_length=32, null=True),
        ),
    ]
