# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0012_auto_20200916_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='anio',
            name='monto_cuota',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuota',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
