# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasocioscap', '0016_auto_20210116_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cobrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemasocioscap.Cobrador'),
        ),
    ]
